# Generated by Django 4.1.3 on 2022-11-29 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=30)),
                ('customer_last_name', models.CharField(max_length=30)),
                ('shipping_address', models.CharField(max_length=60)),
                ('billing_address', models.CharField(max_length=60)),
                ('customer_status', models.CharField(choices=[('PREFFERED', 'preferred'), ('OKAY', 'okay'), ('SHAKY', 'shaky')], default='PREFERRED', max_length=30)),
            ],
            options={
                'verbose_name': 'Customer Information',
                'verbose_name_plural': 'Customer Information Entries',
            },
        ),
        migrations.CreateModel(
            name='orderInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this invoice', primary_key=True, serialize=False)),
                ('order_Quantity', models.PositiveSmallIntegerField(default=1)),
                ('order_Status', models.CharField(choices=[('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='PROCESSING', max_length=30)),
                ('order_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_Item_Flavor', models.ForeignKey(default='Vanilla', on_delete=django.db.models.deletion.CASCADE, to='inventory.flavor')),
                ('order_Shipping', models.ForeignKey(default='Standard', on_delete=django.db.models.deletion.CASCADE, to='inventory.shipping')),
                ('order_Sizes', models.ForeignKey(default='Pint', on_delete=django.db.models.deletion.CASCADE, to='inventory.sizes')),
            ],
            options={
                'verbose_name': 'Order Information',
                'verbose_name_plural': 'Order Information Entries',
            },
        ),
    ]
