# Generated by Django 4.1.3 on 2022-11-29 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='externalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=254)),
                ('ticket_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('BEING WORKED', 'Being Worked'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('ticket_resolution_date', models.DateTimeField(null=True, verbose_name='Problem Resolved')),
            ],
            options={
                'verbose_name': 'External Ticket',
                'verbose_name_plural': 'External Tickets',
            },
        ),
        migrations.CreateModel(
            name='internalTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('ticket_creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(choices=[('INTERNAL PRODUCTION', 'Internal Production'), ('ORDER FULFILLMENT', 'Order Fulfillment'), ('SHIPPING PROBLEMS', 'Shipping Problems'), ('OTHER', 'Other')], max_length=40)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('BEING WORKED', 'Being Worked'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('ticket_resolution_date', models.DateTimeField(null=True, verbose_name='Problem Resolved')),
            ],
            options={
                'verbose_name': 'Internal Ticket',
                'verbose_name_plural': 'Internal Tickets',
            },
        ),
    ]
