# Generated by Django 4.1.3 on 2022-11-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flavor',
            fields=[
                ('flavor', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Flavor',
                'verbose_name_plural': 'Flavors',
            },
        ),
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('type', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=14.99, max_digits=4)),
            ],
            options={
                'verbose_name': 'Shipping',
                'verbose_name_plural': 'Shipping options',
            },
        ),
        migrations.CreateModel(
            name='sizes',
            fields=[
                ('size', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=3.99, max_digits=4)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
    ]
