# Generated by Django 4.1.3 on 2022-11-30 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipmenttracking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shipmentTrack',
        ),
    ]
